apiVersion: apps/v1
kind: Deployment
metadata:
  name: anilsgn-deployment
spec:
  selector:
    matchLabels:
      app: anilsgn-app01
  replicas: 4
  template:
    metadata:
      labels:
        app: anilsgn-app01
    spec:
      containers:
      - name: anilsgn-containers
        image: anilprajapati18/sgndockerpython_01:v1
        ports:
        - containerPort: 5000
