apiVersion: v1
kind: Service
metadata:
  labels:
    app: anilsgn-app01
  name: anilsgn-service
  namespace: default
spec:
  type: NodePort  
  ports:
    - name: http
      protocol: TCP
      port: 5000
  selector:
    app: anilsgn-app01
